apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zot-ingress
  namespace: zot
  labels:
    app: zot
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # or your issuer name
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - registry.k8s.local
      secretName: registry-tls-secret
  rules:
    - host: registry.k8s.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: registry-app-zot
              port:
                number: 5000
