apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist-frontend
  labels:
    app: tasklist-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasklist-frontend
  template:
    metadata:
      labels:
        app: tasklist-frontend
    spec:
      containers:
        - name: frontend
          image: registry.k8s.local/tasklist-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "https://tasklist.k8s.local/api"
            - name: WS_URL
              value: "wss://tasklist.k8s.local/ws"
