apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://zotregistry.dev/helm-charts
    chart: zot
    targetRevision: 0.1.78
    helm:
      values: |
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 10Gi
          storageClass: standard

        service:
          type: ClusterIP
          port: 5000

        config:
          http:
            address: "0.0.0.0"
            port: 5000
          storage:
            rootDirectory: /var/lib/zot
          log:
            level: info

  destination:
    server: https://kubernetes.default.svc
    namespace: zot

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
