apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://zotregistry.dev/helm-charts
    targetRevision: "latest"
    chart: zot
    helm:
      values: |
        # You can override values here if needed
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hosts:
            - zot-registry.local
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
