- hosts: microk8s
  become: true
  roles:
    - role: istvano.microk8s
      vars:
        microk8s_plugins:
          dns: "8.8.8.8"
          istio: true
          ingress: true
          helm: true                             # Helm 3
          helm3: false                             # helm3 is not supported, instead use helm
        users: 
          - "{{ ansible_user }}"
        microk8s_enable_HA: true # enable high-availability?
        microk8s_group_HA: "microk8s" # hostgroup whose members will form high-availability cluster

  tasks:
    - name: Add alias kubectl to .bashrc
      lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: 'alias kubectl="microk8s kubectl"'
        create: yes  # Create the file if it doesn't exist
        state: present  # Ensure the line is present
