---
- name: Create monitoring namespace if it doesn't exist
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "monitoring"
    state: present

- name: Add Prometheus community Helm repo
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install kube-prometheus-stack Helm chart
  community.kubernetes.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: "68.2.1"
    release_namespace: "monitoring"
    create_namespace: false
    values:
      prometheus:
        service:
          type: NodePort
      grafana:
        service:
          type: NodePort
        adminPassword: "admin123"  # Set default admin password
    wait: true

- name: Create Grafana Ingress
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: grafana-ingress
        namespace: monitoring
        labels:
          app: grafana
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 10m
          nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
      spec:
        ingressClassName: nginx
        rules:
          - host: grafana.k8s.local
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: prometheus-grafana
                      port:
                        number: 80
