---
- name: Generate kubeconfig from microk8s
  command: microk8s config
  register: kubeconfig_output

- name: Save kubeconfig to file on remote
  copy:
    content: "{{ kubeconfig_output.stdout }}"
    dest: "/home/{{ ansible_user }}/.kube/config"
    mode: '0600'
    delegate_to: localhost
