---
- name: Copy kubeconfig to local machine if not present
  become: false
  local_action:
    module: copy
    args:
      content: "{{ kubeconfig_output.stdout }}"
      dest: ~/.kube/microk8s_config