apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
  namespace: registry
data:
  config.json: |
    {
      "distSpecVersion": "1.1.0",
      "storage": {
        "rootDirectory": "/var/lib/registry"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000"
      },
      "log": {
        "level": "debug"
      },
      "extensions": {
        "ui": {
          "enable": true
        },
        "search": {
          "enable": true
        }
      }
    }
