- name: Install ArgoCD
  hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core
  vars:
    kubeconfig: ~/.kube/microk8s_config
  tasks:
    - name: Create argocd namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: argocd
        state: present
        kubeconfig: "{{ kubeconfig }}"

    - name: Install ArgoCD manifests
      k8s:
        state: present
        namespace: argocd
        src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        kubeconfig: "{{ kubeconfig }}"
