- name: Install kube-prometheus-stack via Helm
  hosts: localhost
  gather_facts: false
  collections:
    - community.kubernetes
  vars:
    helm_chart_version: "68.2.1"  # Adjust as needed
    release_namespace: "monitoring"
    kubeconfig_path: "~/.kube/microk8s_config"
  tasks:

    - name: Create monitoring namespace if it doesn't exist
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ release_namespace }}"
        state: present
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Add Prometheus community Helm repo
      community.kubernetes.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Install kube-prometheus-stack Helm chart
      community.kubernetes.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        chart_version: "{{ helm_chart_version }}"
        release_namespace: "{{ release_namespace }}"
        kubeconfig: "{{ kubeconfig_path }}"
        create_namespace: false
        values:
          prometheus:
            service:
              type: NodePort
          grafana:
            service:
              type: NodePort
            adminPassword: "admin123"  # Set default admin password
        wait: true
