- hosts: microk8s
  become: true
  vars:
    kubeconfig: ~/.kube/microk8s_config

  roles:
    - role: istvano.microk8s
      vars:
        microk8s_version: "1.33/stable"
        microk8s_plugins:
          dns: "8.8.8.8"
          istio: true
          ingress: true
          helm: true                             # Helm 3
          helm3: false                             # helm3 is not supported, instead use helm
          hostpath-storage: true
        users: 
          - "{{ ansible_user }}"
        microk8s_enable_HA: true # enable high-availability?
        microk8s_group_HA: "microk8s" # hostgroup whose members will form high-availability cluster
        
  tasks:
    - name: Wait for MicroK8s to be ready
      command: microk8s status --wait-ready

    - name: Enable MetalLB with specific IP range
      command: microk8s enable metallb:{{ load_balancer_ip_ranges }}
      register: metallb_result
      changed_when: "'already enabled' not in metallb_result.stdout"
      run_once: true

    - name: Show MetalLB enable message
      debug:
        var: metallb_result.stdout
      run_once: true
