---
- name: Create microk8s cluster
  hosts: microk8s
  become: true
  roles:
    - role: istvano.microk8s
      vars:
        microk8s_version: "1.33/stable"
        microk8s_plugins:
          dns: "{{ dns_servers | join(',') }}"
          istio: true
          ingress: true
          helm: true                             # Helm 3
          helm3: false                             # helm3 is not supported, instead use helm
          hostpath-storage: true
          metallb: "{{ load_balancer_ip_ranges }}"
        users: 
          - "{{ ansible_user }}"
        microk8s_enable_HA: true # enable high-availability?
        microk8s_group_HA: "microk8s" # hostgroup whose members will form high-availability cluster
    - role: microk8s_get_kubeconfig
      vars:
      kubeconfig: ~/.kube/microk8s_config

- name: Infra automation main playbook
  hosts: localhost
  become: true
  gather_facts: false
  roles:
    - role: ssl_create_ca
      tags: [ca]
