{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tasklist.fullname" . }}-ingress
  labels:
    app: {{ include "tasklist.name" . }}
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        # API routes go to the backend
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{ include "tasklist.fullname" $ }}-backend
              port:
                number: {{ $.Values.backend.service.port }}
        # WebSocket routes go to the backend
        - path: /ws
          pathType: Prefix
          backend:
            service:
              name: {{ include "tasklist.fullname" $ }}-backend
              port:
                number: {{ $.Values.backend.service.port }}
        # Everything else goes to the frontend
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "tasklist.fullname" $ }}-frontend
              port:
                number: {{ $.Values.frontend.service.port }}
    {{- end }}
{{- end }}