---
- name: Generate kubeconfig from microk8s
  command: microk8s config
  register: kubeconfig_output

- name: Save kubeconfig to file on remote
  copy:
    content: "{{ kubeconfig_output.stdout }}"
    dest: "/home/{{ ansible_user }}/.kube/config"
    mode: '0600'

- name: Copy kubeconfig to local machine if not present
  become: false
  local_action:
    module: copy
    args:
      content: "{{ kubeconfig_output.stdout }}"
      dest: ~/.kube/microk8s_config
  delegate_to: localhost