apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-build-push
  namespace: devops
spec:
  params:
    - name: git-url
      description: "The Git repository URL"
      type: string
    - name: git-revision
      description: "The Git branch or commit to checkout"
      type: string
    - name: image-name
      description: "The name of the image to build"
      type: string
    - name: context
      description: "The build context"
      type: string
    - name: registry-url
      description: "The container registry URL"
      type: string
    - name: registry-username
      description: "The container registry username"
      type: string
    - name: registry-password
      description: "The container registry password"
      type: string
  steps:
    - name: clone-repo
      image: alpine/git
      script: |
        #!/bin/sh
        echo "Cloning the repository"
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git clone --branch $(params.git-revision) $(params.git-url) /workspace/source
    - name: build-and-push
      image: quay.io/buildah/stable:latest
      securityContext:
        privileged: true
      script: |
        #!/bin/sh
        set -e
        echo "Configuring Buildah for insecure (HTTP) registry"
        mkdir -p /etc/containers
        cat <<EOF > /etc/containers/registries.conf
        [registries.insecure]
        registries = ["$REGISTRY_URL"]
        EOF
        echo "Logging into the container registry"
        #buildah login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD" "$REGISTRY_URL"
        echo "Building the image"
        buildah bud --tls-verify=false -t "$REGISTRY_URL/$IMAGE_NAME:latest" -f "/workspace/source/$CONTEXT/Dockerfile" "/workspace/source/$CONTEXT"
        #buildah bud --tls-verify=false -t "$REGISTRY_URL/$IMAGE_NAME:$GIT_REVISION" -f "/workspace/source/$CONTEXT/Dockerfile" "/workspace/source/$CONTEXT"
        echo "Pushing the image"
        buildah push --tls-verify=false "$REGISTRY_URL/$IMAGE_NAME:latest"
        #buildah push --tls-verify=false "$REGISTRY_URL/$IMAGE_NAME:$GIT_REVISION"
      env:
        - name: REGISTRY_URL
          value: "$(params.registry-url)"
        - name: REGISTRY_USERNAME
          value: "$(params.registry-username)"
        - name: REGISTRY_PASSWORD
          value: "$(params.registry-password)"
        - name: IMAGE_NAME
          value: "$(params.image-name)"
        - name: CONTEXT
          value: "$(params.context)"
        #- name: GIT_REVISION
          #value: "$(params.git-revision)"
  volumes:
    - name: git-ssh-key
      secret:
        secretName: git-deploy-key-secret
